### ISSUE TITLE
CYGNSS Dataset - Downloading and Processing 

### ISSUE THREAD

**Issue by stefanpie** [stefanpie/Stormalytics#43]
http://clasp-research.engin.umich.edu/missions/cygnss/

**Comment by karkir0003** [comment]
Here's my progress right now with the date thing:

For each of the 2018 storms where I grouped by the storm_name, I have the "min date" and "max date" for each storm_name.

**Comment by karkir0003** [comment]
![storm_dates](https://user-images.githubusercontent.com/54720987/75946628-986ccc00-5e6b-11ea-967c-e2c21564def0.PNG)
